# coding: utf8
from __future__ import unicode_literals



TAG_MAP = {  'ABBR__': {'morph': '', 'pos': 'NOUN'}, # NOUN IS HACK FOR ABBR
             'ABBR__Mutation=Aspirate': {'morph': 'Mutation=Aspirate', 'pos': 'NOUN'}, # NOUN IS HACK FOR ABBR
             'ABBR__Mutation=H-initial': {'morph': 'Mutation=H-initial', 'pos': 'NOUN'}, # NOUN IS HACK FOR ABBR
             'ABBR__Mutation=Nasal': {'morph': 'Mutation=Nasal', 'pos': 'NOUN'}, # NOUN IS HACK FOR ABBR
             'ABBR__Mutation=Soft': {'morph': 'Mutation=Soft', 'pos': 'NOUN'}, # NOUN IS HACK FOR ABBR
             'ABBR___': {'morph': '_', 'pos': 'NOUN'}, # NOUN IS HACK FOR ABBR
             'ADJ__Degree=Cmp': {'morph': 'Degree=Cmp', 'pos': 'ADJ'},
             'ADJ__Degree=Cmp|Mutation=Aspirate': {'morph': 'Degree=Cmp|Mutation=Aspirate',
                                                   'pos': 'ADJ'},
             'ADJ__Degree=Cmp|Mutation=H': {'morph': 'Degree=Cmp|Mutation=H', 'pos': 'ADJ'},
             'ADJ__Degree=Cmp|Mutation=Nasal': {'morph': 'Degree=Cmp|Mutation=Nasal',
                                                'pos': 'ADJ'},
             'ADJ__Degree=Cmp|Mutation=Soft': {'morph': 'Degree=Cmp|Mutation=Soft',
                                               'pos': 'ADJ'},
             'ADJ__Degree=Equ': {'morph': 'Degree=Equ', 'pos': 'ADJ'},
             'ADJ__Degree=Equ|Mutation=Aspirate': {'morph': 'Degree=Equ|Mutation=Aspirate',
                                                   'pos': 'ADJ'},
             'ADJ__Degree=Equ|Mutation=H': {'morph': 'Degree=Equ|Mutation=H', 'pos': 'ADJ'},
             'ADJ__Degree=Equ|Mutation=Nasal': {'morph': 'Degree=Equ|Mutation=Nasal',
                                                'pos': 'ADJ'},
             'ADJ__Degree=Equ|Mutation=Soft': {'morph': 'Degree=Equ|Mutation=Soft',
                                               'pos': 'ADJ'},
             'ADJ__Degree=Pos': {'morph': 'Degree=Pos', 'pos': 'ADJ'},
             'ADJ__Degree=Pos|Mutation=Aspirate': {'morph': 'Degree=Pos|Mutation=Aspirate',
                                                   'pos': 'ADJ'},
             'ADJ__Degree=Pos|Mutation=H': {'morph': 'Degree=Pos|Mutation=H', 'pos': 'ADJ'},
             'ADJ__Degree=Pos|Mutation=Nasal': {'morph': 'Degree=Pos|Mutation=Nasal',
                                                'pos': 'ADJ'},
             'ADJ__Degree=Pos|Mutation=Soft': {'morph': 'Degree=Pos|Mutation=Soft',
                                               'pos': 'ADJ'},
             'ADJ__Degree=Sup': {'morph': 'Degree=Sup', 'pos': 'ADJ'},
             'ADJ__Degree=Sup|Mutation=Aspirate': {'morph': 'Degree=Sup|Mutation=Aspirate',
                                                   'pos': 'ADJ'},
             'ADJ__Degree=Sup|Mutation=H': {'morph': 'Degree=Sup|Mutation=H', 'pos': 'ADJ'},
             'ADJ__Degree=Sup|Mutation=Nasal': {'morph': 'Degree=Sup|Mutation=Nasal',
                                                'pos': 'ADJ'},
             'ADJ__Degree=Sup|Mutation=Soft': {'morph': 'Degree=Sup|Mutation=Soft',
                                               'pos': 'ADJ'},
             'ADJ__Mutation=Aspirate': {'morph': 'Mutation=Aspirate', 'pos': 'ADJ'},
             'ADJ__Mutation=H': {'morph': 'Mutation=H', 'pos': 'ADJ'},
             'ADJ__Mutation=Nasal': {'morph': 'Mutation=Nasal', 'pos': 'ADJ'},
             'ADJ__Mutation=Soft': {'morph': 'Mutation=Soft', 'pos': 'ADJ'},
             'ADJ___': {'morph': '_', 'pos': 'ADJ'},
             "ADP___": {"pos": "ADP"},
             'ADV__': {'morph': '', 'pos': 'ADV'},
             'ADV__Mutation=Aspirate': {'morph': 'Mutation=Aspirate', 'pos': 'ADV'},
             'ADV__Mutation=H-initial': {'morph': 'Mutation=H-initial', 'pos': 'ADV'},
             'ADV__Mutation=Nasal': {'morph': 'Mutation=Nasal', 'pos': 'ADV'},
             'ADV__Mutation=Soft': {'morph': 'Mutation=Soft', 'pos': 'ADV'},
             'ADV___': {'morph': '_', 'pos': 'ADV'},
             'CARDF__NumType=Ord|Gender=Fem': {'morph': 'NumType=Ord|Gender=Fem',
                                               'pos': 'NUM'},
             'CARDF__NumType=Ord|Gender=Fem|Mutation=Aspirate': {'morph': 'NumType=Ord|Gender=Fem|Mutation=Aspirate',
                                                                 'pos': 'NUM'},
             'CARDF__NumType=Ord|Gender=Fem|Mutation=H': {'morph': 'NumType=Ord|Gender=Fem|Mutation=H',
                                                          'pos': 'NUM'},
             'CARDF__NumType=Ord|Gender=Fem|Mutation=Nasal': {'morph': 'NumType=Ord|Gender=Fem|Mutation=Nasal',
                                                              'pos': 'NUM'},
             'CARDF__NumType=Ord|Gender=Fem|Mutation=Soft': {'morph': 'NumType=Ord|Gender=Fem|Mutation=Soft',
                                                             'pos': 'NUM'},
             'CONJ__': {'morph': '', 'pos': 'CCONJ'},
             'CONJ__Mutation=Aspirate': {'morph': 'Mutation=Aspirate', 'pos': 'CCONJ'},
             'CONJ__Mutation=H-initial': {'morph': 'Mutation=H-initial', 'pos': 'CCONJ'},
             'CONJ__Mutation=Nasal': {'morph': 'Mutation=Nasal', 'pos': 'CCONJ'},
             'CONJ__Mutation=Soft': {'morph': 'Mutation=Soft', 'pos': 'CCONJ'},
             'CONJ___': {'morph': '_', 'pos': 'CCONJ'},
             'DET__': {'morph': '', 'pos': 'DET'},
             'DET__Mutation=Aspirate': {'morph': 'Mutation=Aspirate', 'pos': 'DET'},
             'DET__Mutation=H-initial': {'morph': 'Mutation=H-initial', 'pos': 'DET'},
             'DET__Mutation=Nasal': {'morph': 'Mutation=Nasal', 'pos': 'DET'},
             'DET__Mutation=Soft': {'morph': 'Mutation=Soft', 'pos': 'DET'},
             'DET___': {'morph': '_', 'pos': 'DET'},
             'INTJ__': {'morph': '', 'pos': 'INTJ'},
             'INTJ__Mutation=Aspirate': {'morph': 'Mutation=Aspirate', 'pos': 'INTJ'},
             'INTJ__Mutation=H-initial': {'morph': 'Mutation=H-initial', 'pos': 'INTJ'},
             'INTJ__Mutation=Nasal': {'morph': 'Mutation=Nasal', 'pos': 'INTJ'},
             'INTJ__Mutation=Soft': {'morph': 'Mutation=Soft', 'pos': 'INTJ'},
             'INTJ___': {'morph': '_', 'pos': 'INTJ'},
             'NF__Gender=Fem|Number=Sing': {'morph': 'Gender=Fem|Number=Sing',
                                            'pos': 'NOUN'},
             'NF__Gender=Fem|Number=Sing|Mutation=Aspirate': {'morph': 'Gender=Fem|Number=Sing|Mutation=Aspirate',
                                                              'pos': 'NOUN'},
             'NF__Gender=Fem|Number=Sing|Mutation=H': {'morph': 'Gender=Fem|Number=Sing|Mutation=H',
                                                       'pos': 'NOUN'},
             'NF__Gender=Fem|Number=Sing|Mutation=Nasal': {'morph': 'Gender=Fem|Number=Sing|Mutation=Nasal',
                                                           'pos': 'NOUN'},
             'NF__Gender=Fem|Number=Sing|Mutation=Soft': {'morph': 'Gender=Fem|Number=Sing|Mutation=Soft',
                                                          'pos': 'NOUN'},
             'NMF__Gender=MascFem|Number=Sing': {'morph': 'Gender=MascFem|Number=Sing',
                                                 'pos': 'NOUN'},
             'NMF__Gender=MascFem|Number=Sing|Mutation=Aspirate': {'morph': 'Gender=MascFem|Number=Sing|Mutation=Aspirate',
                                                                   'pos': 'NOUN'},
             'NMF__Gender=MascFem|Number=Sing|Mutation=H': {'morph': 'Gender=MascFem|Number=Sing|Mutation=H',
                                                            'pos': 'NOUN'},
             'NMF__Gender=MascFem|Number=Sing|Mutation=Nasal': {'morph': 'Gender=MascFem|Number=Sing|Mutation=Nasal',
                                                                'pos': 'NOUN'},
             'NMF__Gender=MascFem|Number=Sing|Mutation=Soft': {'morph': 'Gender=MascFem|Number=Sing|Mutation=Soft',
                                                               'pos': 'NOUN'},
             'NM__Gender=Masc|Number=Sing': {'morph': 'Gender=Masc|Number=Sing',
                                             'pos': 'NOUN'},
             'NM__Gender=Masc|Number=Sing|Mutation=Aspirate': {'morph': 'Gender=Masc|Number=Sing|Mutation=Aspirate',
                                                               'pos': 'NOUN'},
             'NM__Gender=Masc|Number=Sing|Mutation=H': {'morph': 'Gender=Masc|Number=Sing|Mutation=H',
                                                        'pos': 'NOUN'},
             'NM__Gender=Masc|Number=Sing|Mutation=Nasal': {'morph': 'Gender=Masc|Number=Sing|Mutation=Nasal',
                                                            'pos': 'NOUN'},
             'NM__Gender=Masc|Number=Sing|Mutation=Soft': {'morph': 'Gender=Masc|Number=Sing|Mutation=Soft',
                                                           'pos': 'NOUN'},
             'NPLACE___': {'morph': '_', 'pos': 'PROPN'},
             'NPLACE__Mutation=Nasal': {'morph': 'Mutation=Nasal', 'pos': 'PROPN'},
             'NPLACE__Mutation=Soft': {'morph': 'Mutation=Soft', 'pos': 'PROPN'},
             'NPLACE__Mutation=Aspirate': {'morph': 'Mutation=Aspirate', 'pos': 'PROPN'},
             'NPL__Number=Plur': {'morph': 'Number=Plur', 'pos': 'NOUN'},
             'NPL__Number=Plur|Mutation=Aspirate': {'morph': 'Number=Plur|Mutation=Aspirate',
                                                    'pos': 'NOUN'},
             'NPL__Number=Plur|Mutation=H': {'morph': 'Number=Plur|Mutation=H',
                                             'pos': 'NOUN'},
             'NPL__Number=Plur|Mutation=Nasal': {'morph': 'Number=Plur|Mutation=Nasal',
                                                 'pos': 'NOUN'},
             'NPL__Number=Plur|Mutation=Soft': {'morph': 'Number=Plur|Mutation=Soft',
                                                'pos': 'NOUN'},
             'NPL___': {'morph': '_', 'pos': 'PROPN'},
             'ORD__NumType=Ord': {'morph': 'NumType=Ord', 'pos': 'NUM'},
             'ORD__NumType=Ord|Mutation=Aspirate': {'morph': 'NumType=Ord|Mutation=Aspirate',
                                                    'pos': 'NUM'},
             'ORD__NumType=Ord|Mutation=H': {'morph': 'NumType=Ord|Mutation=H',
                                             'pos': 'NUM'},
             'ORD__NumType=Ord|Mutation=Nasal': {'morph': 'NumType=Ord|Mutation=Nasal',
                                                 'pos': 'NUM'},
             'ORD__NumType=Ord|Mutation=Soft': {'morph': 'NumType=Ord|Mutation=Soft',
                                                'pos': 'NUM'},
             'PART__': {'morph': '', 'pos': 'PART'},
             'PART__Mutation=H-initial': {'morph': 'Mutation=H-initial', 'pos': 'PART'},
             'PART___': {'morph': '_', 'pos': 'PART'},
             'PREF__': {'morph': '', 'pos': 'ADP'}, # HACK
             'PREF__Mutation=Aspirate': {'morph': 'Mutation=Aspirate', 'pos': 'ADP'}, # HACK
             'PREF__Mutation=H-initial': {'morph': 'Mutation=H-initial', 'pos': 'ADP'}, # HACK
             'PREF__Mutation=Nasal': {'morph': 'Mutation=Nasal', 'pos': 'ADP'}, # HACK
             'PREF__Mutation=Soft': {'morph': 'Mutation=Soft', 'pos': 'ADP'}, # HACK
             'PREF___': {'morph': '_', 'pos': 'ADP'},
             'PREP__': {'morph': '', 'pos': 'ADP'},
             'PREP__Mutation=Aspirate': {'morph': 'Mutation=Aspirate', 'pos': 'ADP'},
             'PREP__Mutation=H-initial': {'morph': 'Mutation=H-initial', 'pos': 'ADP'},
             'PREP__Mutation=Nasal': {'morph': 'Mutation=Nasal', 'pos': 'ADP'},
             'PREP__Mutation=Soft': {'morph': 'Mutation=Soft', 'pos': 'ADP'},
             'PREP___': {'morph': '_', 'pos': 'ADP'},
             'PRON__': {'morph': '', 'pos': 'PRON'},
             'PRON__Mutation=Aspirate': {'morph': 'Mutation=Aspirate', 'pos': 'PRON'},
             'PRON__Mutation=H-initial': {'morph': 'Mutation=H-initial', 'pos': 'PRON'},
             'PRON__Mutation=Nasal': {'morph': 'Mutation=Nasal', 'pos': 'PRON'},
             'PRON__Mutation=Soft': {'morph': 'Mutation=Soft', 'pos': 'PRON'},
             'PRON___': {'morph': '_', 'pos': 'PRON'},
             'AUX__': {'morph': '', 'pos': 'AUX'},
             'AUX__Mutation=H-initial': {'morph': 'Mutation=H-initial', 'pos': 'AUX'},
             'AUX___': {'morph': '_', 'pos': 'AUX'},
             'VERBNOUN__Mutation=Aspirate': {'morph': 'Mutation=Aspirate', 'pos': 'NOUN'},
             'VERBNOUN__Mutation=H': {'morph': 'Mutation=H', 'pos': 'NOUN'},
             'VERBNOUN__Mutation=Nasal': {'morph': 'Mutation=Nasal', 'pos': 'NOUN'},
             'VERBNOUN__Mutation=Soft': {'morph': 'Mutation=Soft', 'pos': 'NOUN'},
             'VERBNOUN__': {'morph': '_', 'pos': 'NOUN'},
             'VBF__Tense=Pres': {'morph': 'Tense=Dibynnol', 'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Dibynnol': {'morph': 'Person=1|Number=Plur|Tense=Dibynnol',
                                                           'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Dibynnol|Mutation=Aspirate': {'morph': 'Person=1|Number=Plur|Tense=Dibynnol|Mutation=Aspirate',
                                                                             'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Dibynnol|Mutation=H': {'morph': 'Person=1|Number=Plur|Tense=Dibynnol|Mutation=H',
                                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Dibynnol|Mutation=Nasal': {'morph': 'Person=1|Number=Plur|Tense=Dibynnol|Mutation=Nasal',
                                                                          'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Dibynnol|Mutation=Soft': {'morph': 'Person=1|Number=Plur|Tense=Dibynnol|Mutation=Soft',
                                                                         'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Imp': {'morph': 'Person=1|Number=Plur|Tense=Imp',
                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Imperative[Mood?]': {'morph': 'Person=1|Number=Plur|Tense=Imperative[Mood?]',
                                                                    'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Imperative[Mood?]|Mutation=Aspirate': {'morph': 'Person=1|Number=Plur|Tense=Imperative[Mood?]|Mutation=Aspirate',
                                                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Imperative[Mood?]|Mutation=H': {'morph': 'Person=1|Number=Plur|Tense=Imperative[Mood?]|Mutation=H',
                                                                               'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Imperative[Mood?]|Mutation=Nasal': {'morph': 'Person=1|Number=Plur|Tense=Imperative[Mood?]|Mutation=Nasal',
                                                                                   'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Imperative[Mood?]|Mutation=Soft': {'morph': 'Person=1|Number=Plur|Tense=Imperative[Mood?]|Mutation=Soft',
                                                                                  'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Imp|Mutation=Aspirate': {'morph': 'Person=1|Number=Plur|Tense=Imp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Imp|Mutation=H': {'morph': 'Person=1|Number=Plur|Tense=Imp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Imp|Mutation=Nasal': {'morph': 'Person=1|Number=Plur|Tense=Imp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Imp|Mutation=Soft': {'morph': 'Person=1|Number=Plur|Tense=Imp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Past': {'morph': 'Person=1|Number=Plur|Tense=Past',
                                                       'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Past|Mutation=Aspirate': {'morph': 'Person=1|Number=Plur|Tense=Past|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Past|Mutation=H': {'morph': 'Person=1|Number=Plur|Tense=Past|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Past|Mutation=Nasal': {'morph': 'Person=1|Number=Plur|Tense=Past|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Past|Mutation=Soft': {'morph': 'Person=1|Number=Plur|Tense=Past|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Pqp': {'morph': 'Person=1|Number=Plur|Tense=Pqp',
                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Pqp|Mutation=Aspirate': {'morph': 'Person=1|Number=Plur|Tense=Pqp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Pqp|Mutation=H': {'morph': 'Person=1|Number=Plur|Tense=Pqp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Pqp|Mutation=Nasal': {'morph': 'Person=1|Number=Plur|Tense=Pqp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Pqp|Mutation=Soft': {'morph': 'Person=1|Number=Plur|Tense=Pqp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Pres': {'morph': 'Person=1|Number=Plur|Tense=Pres',
                                                       'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Pres|Mutation=Aspirate': {'morph': 'Person=1|Number=Plur|Tense=Pres|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Pres|Mutation=H': {'morph': 'Person=1|Number=Plur|Tense=Pres|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Pres|Mutation=Nasal': {'morph': 'Person=1|Number=Plur|Tense=Pres|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=Pres|Mutation=Soft': {'morph': 'Person=1|Number=Plur|Tense=Pres|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=bod_amherffaith': {'morph': 'Person=1|Number=Plur|Tense=bod_amherffaith',
                                                                  'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=bod_amherffaith|Mutation=Aspirate': {'morph': 'Person=1|Number=Plur|Tense=bod_amherffaith|Mutation=Aspirate',
                                                                                    'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=bod_amherffaith|Mutation=H': {'morph': 'Person=1|Number=Plur|Tense=bod_amherffaith|Mutation=H',
                                                                             'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=bod_amherffaith|Mutation=Nasal': {'morph': 'Person=1|Number=Plur|Tense=bod_amherffaith|Mutation=Nasal',
                                                                                 'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=bod_amherffaith|Mutation=Soft': {'morph': 'Person=1|Number=Plur|Tense=bod_amherffaith|Mutation=Soft',
                                                                                'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=bod_dyfodol': {'morph': 'Person=1|Number=Plur|Tense=bod_dyfodol',
                                                              'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=bod_dyfodol|Mutation=Aspirate': {'morph': 'Person=1|Number=Plur|Tense=bod_dyfodol|Mutation=Aspirate',
                                                                                'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=bod_dyfodol|Mutation=H': {'morph': 'Person=1|Number=Plur|Tense=bod_dyfodol|Mutation=H',
                                                                         'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=bod_dyfodol|Mutation=Nasal': {'morph': 'Person=1|Number=Plur|Tense=bod_dyfodol|Mutation=Nasal',
                                                                             'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=bod_dyfodol|Mutation=Soft': {'morph': 'Person=1|Number=Plur|Tense=bod_dyfodol|Mutation=Soft',
                                                                            'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=dibynnol_amherffaith': {'morph': 'Person=1|Number=Plur|Tense=dibynnol_amherffaith',
                                                                       'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Aspirate': {'morph': 'Person=1|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Aspirate',
                                                                                         'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=dibynnol_amherffaith|Mutation=H': {'morph': 'Person=1|Number=Plur|Tense=dibynnol_amherffaith|Mutation=H',
                                                                                  'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Nasal': {'morph': 'Person=1|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Nasal',
                                                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Soft': {'morph': 'Person=1|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Soft',
                                                                                     'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Dibynnol': {'morph': 'Person=1|Number=Sing|Tense=Dibynnol',
                                                           'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Dibynnol|Mutation=Aspirate': {'morph': 'Person=1|Number=Sing|Tense=Dibynnol|Mutation=Aspirate',
                                                                             'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Dibynnol|Mutation=H': {'morph': 'Person=1|Number=Sing|Tense=Dibynnol|Mutation=H',
                                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Dibynnol|Mutation=Nasal': {'morph': 'Person=1|Number=Sing|Tense=Dibynnol|Mutation=Nasal',
                                                                          'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Dibynnol|Mutation=Soft': {'morph': 'Person=1|Number=Sing|Tense=Dibynnol|Mutation=Soft',
                                                                         'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Imp': {'morph': 'Person=1|Number=Sing|Tense=Imp',
                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Imp|Mutation=Aspirate': {'morph': 'Person=1|Number=Sing|Tense=Imp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Imp|Mutation=H': {'morph': 'Person=1|Number=Sing|Tense=Imp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Imp|Mutation=Nasal': {'morph': 'Person=1|Number=Sing|Tense=Imp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Imp|Mutation=Soft': {'morph': 'Person=1|Number=Sing|Tense=Imp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Past': {'morph': 'Person=1|Number=Sing|Tense=Past',
                                                       'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Past|Mutation=Aspirate': {'morph': 'Person=1|Number=Sing|Tense=Past|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Past|Mutation=H': {'morph': 'Person=1|Number=Sing|Tense=Past|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Past|Mutation=Nasal': {'morph': 'Person=1|Number=Sing|Tense=Past|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Past|Mutation=Soft': {'morph': 'Person=1|Number=Sing|Tense=Past|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Pqp': {'morph': 'Person=1|Number=Sing|Tense=Pqp',
                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Pqp|Mutation=Aspirate': {'morph': 'Person=1|Number=Sing|Tense=Pqp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Pqp|Mutation=H': {'morph': 'Person=1|Number=Sing|Tense=Pqp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Pqp|Mutation=Nasal': {'morph': 'Person=1|Number=Sing|Tense=Pqp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Pqp|Mutation=Soft': {'morph': 'Person=1|Number=Sing|Tense=Pqp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Pres': {'morph': 'Person=1|Number=Sing|Tense=Pres',
                                                       'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Pres|Mutation=Aspirate': {'morph': 'Person=1|Number=Sing|Tense=Pres|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Pres|Mutation=H': {'morph': 'Person=1|Number=Sing|Tense=Pres|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Pres|Mutation=Nasal': {'morph': 'Person=1|Number=Sing|Tense=Pres|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=Pres|Mutation=Soft': {'morph': 'Person=1|Number=Sing|Tense=Pres|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=bod_amherffaith': {'morph': 'Person=1|Number=Sing|Tense=bod_amherffaith',
                                                                  'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=bod_amherffaith|Mutation=Aspirate': {'morph': 'Person=1|Number=Sing|Tense=bod_amherffaith|Mutation=Aspirate',
                                                                                    'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=bod_amherffaith|Mutation=H': {'morph': 'Person=1|Number=Sing|Tense=bod_amherffaith|Mutation=H',
                                                                             'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=bod_amherffaith|Mutation=Nasal': {'morph': 'Person=1|Number=Sing|Tense=bod_amherffaith|Mutation=Nasal',
                                                                                 'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=bod_amherffaith|Mutation=Soft': {'morph': 'Person=1|Number=Sing|Tense=bod_amherffaith|Mutation=Soft',
                                                                                'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=bod_dyfodol': {'morph': 'Person=1|Number=Sing|Tense=bod_dyfodol',
                                                              'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=bod_dyfodol|Mutation=Aspirate': {'morph': 'Person=1|Number=Sing|Tense=bod_dyfodol|Mutation=Aspirate',
                                                                                'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=bod_dyfodol|Mutation=H': {'morph': 'Person=1|Number=Sing|Tense=bod_dyfodol|Mutation=H',
                                                                         'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=bod_dyfodol|Mutation=Nasal': {'morph': 'Person=1|Number=Sing|Tense=bod_dyfodol|Mutation=Nasal',
                                                                             'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=bod_dyfodol|Mutation=Soft': {'morph': 'Person=1|Number=Sing|Tense=bod_dyfodol|Mutation=Soft',
                                                                            'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=dibynnol_amherffaith': {'morph': 'Person=1|Number=Sing|Tense=dibynnol_amherffaith',
                                                                       'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Aspirate': {'morph': 'Person=1|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Aspirate',
                                                                                         'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=dibynnol_amherffaith|Mutation=H': {'morph': 'Person=1|Number=Sing|Tense=dibynnol_amherffaith|Mutation=H',
                                                                                  'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Nasal': {'morph': 'Person=1|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Nasal',
                                                                                      'pos': 'VERB'},
             'VBF__Person=1|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Soft': {'morph': 'Person=1|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Soft',
                                                                                     'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Dibynnol': {'morph': 'Person=2|Number=Plur|Tense=Dibynnol',
                                                           'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Dibynnol|Mutation=Aspirate': {'morph': 'Person=2|Number=Plur|Tense=Dibynnol|Mutation=Aspirate',
                                                                             'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Dibynnol|Mutation=H': {'morph': 'Person=2|Number=Plur|Tense=Dibynnol|Mutation=H',
                                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Dibynnol|Mutation=Nasal': {'morph': 'Person=2|Number=Plur|Tense=Dibynnol|Mutation=Nasal',
                                                                          'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Dibynnol|Mutation=Soft': {'morph': 'Person=2|Number=Plur|Tense=Dibynnol|Mutation=Soft',
                                                                         'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Imp': {'morph': 'Person=2|Number=Plur|Tense=Imp',
                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Imperative[Mood?]': {'morph': 'Person=2|Number=Plur|Tense=Imperative[Mood?]',
                                                                    'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Imperative[Mood?]|Mutation=Aspirate': {'morph': 'Person=2|Number=Plur|Tense=Imperative[Mood?]|Mutation=Aspirate',
                                                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Imperative[Mood?]|Mutation=H': {'morph': 'Person=2|Number=Plur|Tense=Imperative[Mood?]|Mutation=H',
                                                                               'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Imperative[Mood?]|Mutation=Nasal': {'morph': 'Person=2|Number=Plur|Tense=Imperative[Mood?]|Mutation=Nasal',
                                                                                   'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Imperative[Mood?]|Mutation=Soft': {'morph': 'Person=2|Number=Plur|Tense=Imperative[Mood?]|Mutation=Soft',
                                                                                  'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Imp|Mutation=Aspirate': {'morph': 'Person=2|Number=Plur|Tense=Imp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Imp|Mutation=H': {'morph': 'Person=2|Number=Plur|Tense=Imp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Imp|Mutation=Nasal': {'morph': 'Person=2|Number=Plur|Tense=Imp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Imp|Mutation=Soft': {'morph': 'Person=2|Number=Plur|Tense=Imp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Past': {'morph': 'Person=2|Number=Plur|Tense=Past',
                                                       'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Past|Mutation=Aspirate': {'morph': 'Person=2|Number=Plur|Tense=Past|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Past|Mutation=H': {'morph': 'Person=2|Number=Plur|Tense=Past|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Past|Mutation=Nasal': {'morph': 'Person=2|Number=Plur|Tense=Past|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Past|Mutation=Soft': {'morph': 'Person=2|Number=Plur|Tense=Past|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Pqp': {'morph': 'Person=2|Number=Plur|Tense=Pqp',
                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Pqp|Mutation=Aspirate': {'morph': 'Person=2|Number=Plur|Tense=Pqp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Pqp|Mutation=H': {'morph': 'Person=2|Number=Plur|Tense=Pqp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Pqp|Mutation=Nasal': {'morph': 'Person=2|Number=Plur|Tense=Pqp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Pqp|Mutation=Soft': {'morph': 'Person=2|Number=Plur|Tense=Pqp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Pres': {'morph': 'Person=2|Number=Plur|Tense=Pres',
                                                       'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Pres|Mutation=Aspirate': {'morph': 'Person=2|Number=Plur|Tense=Pres|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Pres|Mutation=H': {'morph': 'Person=2|Number=Plur|Tense=Pres|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Pres|Mutation=Nasal': {'morph': 'Person=2|Number=Plur|Tense=Pres|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=Pres|Mutation=Soft': {'morph': 'Person=2|Number=Plur|Tense=Pres|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=bod_amherffaith': {'morph': 'Person=2|Number=Plur|Tense=bod_amherffaith',
                                                                  'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=bod_amherffaith|Mutation=Aspirate': {'morph': 'Person=2|Number=Plur|Tense=bod_amherffaith|Mutation=Aspirate',
                                                                                    'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=bod_amherffaith|Mutation=H': {'morph': 'Person=2|Number=Plur|Tense=bod_amherffaith|Mutation=H',
                                                                             'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=bod_amherffaith|Mutation=Nasal': {'morph': 'Person=2|Number=Plur|Tense=bod_amherffaith|Mutation=Nasal',
                                                                                 'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=bod_amherffaith|Mutation=Soft': {'morph': 'Person=2|Number=Plur|Tense=bod_amherffaith|Mutation=Soft',
                                                                                'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=bod_dyfodol': {'morph': 'Person=2|Number=Plur|Tense=bod_dyfodol',
                                                              'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=bod_dyfodol|Mutation=Aspirate': {'morph': 'Person=2|Number=Plur|Tense=bod_dyfodol|Mutation=Aspirate',
                                                                                'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=bod_dyfodol|Mutation=H': {'morph': 'Person=2|Number=Plur|Tense=bod_dyfodol|Mutation=H',
                                                                         'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=bod_dyfodol|Mutation=Nasal': {'morph': 'Person=2|Number=Plur|Tense=bod_dyfodol|Mutation=Nasal',
                                                                             'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=bod_dyfodol|Mutation=Soft': {'morph': 'Person=2|Number=Plur|Tense=bod_dyfodol|Mutation=Soft',
                                                                            'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=dibynnol_amherffaith': {'morph': 'Person=2|Number=Plur|Tense=dibynnol_amherffaith',
                                                                       'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Aspirate': {'morph': 'Person=2|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Aspirate',
                                                                                         'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=dibynnol_amherffaith|Mutation=H': {'morph': 'Person=2|Number=Plur|Tense=dibynnol_amherffaith|Mutation=H',
                                                                                  'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Nasal': {'morph': 'Person=2|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Nasal',
                                                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Soft': {'morph': 'Person=2|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Soft',
                                                                                     'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Dibynnol': {'morph': 'Person=2|Number=Sing|Tense=Dibynnol',
                                                           'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Dibynnol|Mutation=Aspirate': {'morph': 'Person=2|Number=Sing|Tense=Dibynnol|Mutation=Aspirate',
                                                                             'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Dibynnol|Mutation=H': {'morph': 'Person=2|Number=Sing|Tense=Dibynnol|Mutation=H',
                                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Dibynnol|Mutation=Nasal': {'morph': 'Person=2|Number=Sing|Tense=Dibynnol|Mutation=Nasal',
                                                                          'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Dibynnol|Mutation=Soft': {'morph': 'Person=2|Number=Sing|Tense=Dibynnol|Mutation=Soft',
                                                                         'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Imp': {'morph': 'Person=2|Number=Sing|Tense=Imp',
                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Imperative[Mood?]': {'morph': 'Person=2|Number=Sing|Tense=Imperative[Mood?]',
                                                                    'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Imperative[Mood?]|Mutation=Aspirate': {'morph': 'Person=2|Number=Sing|Tense=Imperative[Mood?]|Mutation=Aspirate',
                                                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Imperative[Mood?]|Mutation=H': {'morph': 'Person=2|Number=Sing|Tense=Imperative[Mood?]|Mutation=H',
                                                                               'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Imperative[Mood?]|Mutation=Nasal': {'morph': 'Person=2|Number=Sing|Tense=Imperative[Mood?]|Mutation=Nasal',
                                                                                   'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Imperative[Mood?]|Mutation=Soft': {'morph': 'Person=2|Number=Sing|Tense=Imperative[Mood?]|Mutation=Soft',
                                                                                  'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Imp|Mutation=Aspirate': {'morph': 'Person=2|Number=Sing|Tense=Imp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Imp|Mutation=H': {'morph': 'Person=2|Number=Sing|Tense=Imp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Imp|Mutation=Nasal': {'morph': 'Person=2|Number=Sing|Tense=Imp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Imp|Mutation=Soft': {'morph': 'Person=2|Number=Sing|Tense=Imp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Past': {'morph': 'Person=2|Number=Sing|Tense=Past',
                                                       'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Past|Mutation=Aspirate': {'morph': 'Person=2|Number=Sing|Tense=Past|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Past|Mutation=H': {'morph': 'Person=2|Number=Sing|Tense=Past|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Past|Mutation=Nasal': {'morph': 'Person=2|Number=Sing|Tense=Past|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Past|Mutation=Soft': {'morph': 'Person=2|Number=Sing|Tense=Past|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Pqp': {'morph': 'Person=2|Number=Sing|Tense=Pqp',
                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Pqp|Mutation=Aspirate': {'morph': 'Person=2|Number=Sing|Tense=Pqp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Pqp|Mutation=H': {'morph': 'Person=2|Number=Sing|Tense=Pqp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Pqp|Mutation=Nasal': {'morph': 'Person=2|Number=Sing|Tense=Pqp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Pqp|Mutation=Soft': {'morph': 'Person=2|Number=Sing|Tense=Pqp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Pres': {'morph': 'Person=2|Number=Sing|Tense=Pres',
                                                       'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Pres|Mutation=Aspirate': {'morph': 'Person=2|Number=Sing|Tense=Pres|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Pres|Mutation=H': {'morph': 'Person=2|Number=Sing|Tense=Pres|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Pres|Mutation=Nasal': {'morph': 'Person=2|Number=Sing|Tense=Pres|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=Pres|Mutation=Soft': {'morph': 'Person=2|Number=Sing|Tense=Pres|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=bod_amherffaith': {'morph': 'Person=2|Number=Sing|Tense=bod_amherffaith',
                                                                  'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=bod_amherffaith|Mutation=Aspirate': {'morph': 'Person=2|Number=Sing|Tense=bod_amherffaith|Mutation=Aspirate',
                                                                                    'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=bod_amherffaith|Mutation=H': {'morph': 'Person=2|Number=Sing|Tense=bod_amherffaith|Mutation=H',
                                                                             'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=bod_amherffaith|Mutation=Nasal': {'morph': 'Person=2|Number=Sing|Tense=bod_amherffaith|Mutation=Nasal',
                                                                                 'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=bod_amherffaith|Mutation=Soft': {'morph': 'Person=2|Number=Sing|Tense=bod_amherffaith|Mutation=Soft',
                                                                                'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=bod_dyfodol': {'morph': 'Person=2|Number=Sing|Tense=bod_dyfodol',
                                                              'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=bod_dyfodol|Mutation=Aspirate': {'morph': 'Person=2|Number=Sing|Tense=bod_dyfodol|Mutation=Aspirate',
                                                                                'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=bod_dyfodol|Mutation=H': {'morph': 'Person=2|Number=Sing|Tense=bod_dyfodol|Mutation=H',
                                                                         'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=bod_dyfodol|Mutation=Nasal': {'morph': 'Person=2|Number=Sing|Tense=bod_dyfodol|Mutation=Nasal',
                                                                             'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=bod_dyfodol|Mutation=Soft': {'morph': 'Person=2|Number=Sing|Tense=bod_dyfodol|Mutation=Soft',
                                                                            'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=dibynnol_amherffaith': {'morph': 'Person=2|Number=Sing|Tense=dibynnol_amherffaith',
                                                                       'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Aspirate': {'morph': 'Person=2|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Aspirate',
                                                                                         'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=dibynnol_amherffaith|Mutation=H': {'morph': 'Person=2|Number=Sing|Tense=dibynnol_amherffaith|Mutation=H',
                                                                                  'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Nasal': {'morph': 'Person=2|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Nasal',
                                                                                      'pos': 'VERB'},
             'VBF__Person=2|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Soft': {'morph': 'Person=2|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Soft',
                                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Dibynnol': {'morph': 'Person=3|Number=Plur|Tense=Dibynnol',
                                                           'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Dibynnol|Mutation=Aspirate': {'morph': 'Person=3|Number=Plur|Tense=Dibynnol|Mutation=Aspirate',
                                                                             'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Dibynnol|Mutation=H': {'morph': 'Person=3|Number=Plur|Tense=Dibynnol|Mutation=H',
                                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Dibynnol|Mutation=Nasal': {'morph': 'Person=3|Number=Plur|Tense=Dibynnol|Mutation=Nasal',
                                                                          'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Dibynnol|Mutation=Soft': {'morph': 'Person=3|Number=Plur|Tense=Dibynnol|Mutation=Soft',
                                                                         'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Fut': {'morph': 'Person=3|Number=Plur|Tense=Fut',
                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Fut|Mutation=Aspirate': {'morph': 'Person=3|Number=Plur|Tense=Fut|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Fut|Mutation=H': {'morph': 'Person=3|Number=Plur|Tense=Fut|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Fut|Mutation=Nasal': {'morph': 'Person=3|Number=Plur|Tense=Fut|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Fut|Mutation=Soft': {'morph': 'Person=3|Number=Plur|Tense=Fut|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Imp': {'morph': 'Person=3|Number=Plur|Tense=Imp',
                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Imperative[Mood?]': {'morph': 'Person=3|Number=Plur|Tense=Imperative[Mood?]',
                                                                    'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Imperative[Mood?]|Mutation=Aspirate': {'morph': 'Person=3|Number=Plur|Tense=Imperative[Mood?]|Mutation=Aspirate',
                                                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Imperative[Mood?]|Mutation=H': {'morph': 'Person=3|Number=Plur|Tense=Imperative[Mood?]|Mutation=H',
                                                                               'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Imperative[Mood?]|Mutation=Nasal': {'morph': 'Person=3|Number=Plur|Tense=Imperative[Mood?]|Mutation=Nasal',
                                                                                   'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Imperative[Mood?]|Mutation=Soft': {'morph': 'Person=3|Number=Plur|Tense=Imperative[Mood?]|Mutation=Soft',
                                                                                  'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Imp|Mutation=Aspirate': {'morph': 'Person=3|Number=Plur|Tense=Imp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Imp|Mutation=H': {'morph': 'Person=3|Number=Plur|Tense=Imp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Imp|Mutation=Nasal': {'morph': 'Person=3|Number=Plur|Tense=Imp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Imp|Mutation=Soft': {'morph': 'Person=3|Number=Plur|Tense=Imp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Past': {'morph': 'Person=3|Number=Plur|Tense=Past',
                                                       'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Past|Mutation=Aspirate': {'morph': 'Person=3|Number=Plur|Tense=Past|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Past|Mutation=H': {'morph': 'Person=3|Number=Plur|Tense=Past|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Past|Mutation=Nasal': {'morph': 'Person=3|Number=Plur|Tense=Past|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Past|Mutation=Soft': {'morph': 'Person=3|Number=Plur|Tense=Past|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Pqp': {'morph': 'Person=3|Number=Plur|Tense=Pqp',
                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Pqp|Mutation=Aspirate': {'morph': 'Person=3|Number=Plur|Tense=Pqp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Pqp|Mutation=H': {'morph': 'Person=3|Number=Plur|Tense=Pqp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Pqp|Mutation=Nasal': {'morph': 'Person=3|Number=Plur|Tense=Pqp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Pqp|Mutation=Soft': {'morph': 'Person=3|Number=Plur|Tense=Pqp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Pres': {'morph': 'Person=3|Number=Plur|Tense=Pres',
                                                       'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Pres|Mutation=Aspirate': {'morph': 'Person=3|Number=Plur|Tense=Pres|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Pres|Mutation=H': {'morph': 'Person=3|Number=Plur|Tense=Pres|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Pres|Mutation=Nasal': {'morph': 'Person=3|Number=Plur|Tense=Pres|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=Pres|Mutation=Soft': {'morph': 'Person=3|Number=Plur|Tense=Pres|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=bod_amherffaith': {'morph': 'Person=3|Number=Plur|Tense=bod_amherffaith',
                                                                  'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=bod_amherffaith|Mutation=Aspirate': {'morph': 'Person=3|Number=Plur|Tense=bod_amherffaith|Mutation=Aspirate',
                                                                                    'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=bod_amherffaith|Mutation=H': {'morph': 'Person=3|Number=Plur|Tense=bod_amherffaith|Mutation=H',
                                                                             'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=bod_amherffaith|Mutation=Nasal': {'morph': 'Person=3|Number=Plur|Tense=bod_amherffaith|Mutation=Nasal',
                                                                                 'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=bod_amherffaith|Mutation=Soft': {'morph': 'Person=3|Number=Plur|Tense=bod_amherffaith|Mutation=Soft',
                                                                                'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=bod_dyfodol': {'morph': 'Person=3|Number=Plur|Tense=bod_dyfodol',
                                                              'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=bod_dyfodol|Mutation=Aspirate': {'morph': 'Person=3|Number=Plur|Tense=bod_dyfodol|Mutation=Aspirate',
                                                                                'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=bod_dyfodol|Mutation=H': {'morph': 'Person=3|Number=Plur|Tense=bod_dyfodol|Mutation=H',
                                                                         'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=bod_dyfodol|Mutation=Nasal': {'morph': 'Person=3|Number=Plur|Tense=bod_dyfodol|Mutation=Nasal',
                                                                             'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=bod_dyfodol|Mutation=Soft': {'morph': 'Person=3|Number=Plur|Tense=bod_dyfodol|Mutation=Soft',
                                                                            'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=dibynnol_amherffaith': {'morph': 'Person=3|Number=Plur|Tense=dibynnol_amherffaith',
                                                                       'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Aspirate': {'morph': 'Person=3|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Aspirate',
                                                                                         'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=dibynnol_amherffaith|Mutation=H': {'morph': 'Person=3|Number=Plur|Tense=dibynnol_amherffaith|Mutation=H',
                                                                                  'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Nasal': {'morph': 'Person=3|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Nasal',
                                                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Soft': {'morph': 'Person=3|Number=Plur|Tense=dibynnol_amherffaith|Mutation=Soft',
                                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Dibynnol': {'morph': 'Person=3|Number=Sing|Tense=Dibynnol',
                                                           'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Dibynnol|Mutation=Aspirate': {'morph': 'Person=3|Number=Sing|Tense=Dibynnol|Mutation=Aspirate',
                                                                             'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Dibynnol|Mutation=H': {'morph': 'Person=3|Number=Sing|Tense=Dibynnol|Mutation=H',
                                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Dibynnol|Mutation=Nasal': {'morph': 'Person=3|Number=Sing|Tense=Dibynnol|Mutation=Nasal',
                                                                          'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Dibynnol|Mutation=Soft': {'morph': 'Person=3|Number=Sing|Tense=Dibynnol|Mutation=Soft',
                                                                         'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Fut': {'morph': 'Person=3|Number=Sing|Tense=Fut',
                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Fut|Mutation=Aspirate': {'morph': 'Person=3|Number=Sing|Tense=Fut|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Fut|Mutation=H': {'morph': 'Person=3|Number=Sing|Tense=Fut|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Fut|Mutation=Nasal': {'morph': 'Person=3|Number=Sing|Tense=Fut|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Fut|Mutation=Soft': {'morph': 'Person=3|Number=Sing|Tense=Fut|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Imp': {'morph': 'Person=3|Number=Sing|Tense=Imp',
                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Imperative[Mood?]': {'morph': 'Person=3|Number=Sing|Tense=Imperative[Mood?]',
                                                                    'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Imperative[Mood?]|Mutation=Aspirate': {'morph': 'Person=3|Number=Sing|Tense=Imperative[Mood?]|Mutation=Aspirate',
                                                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Imperative[Mood?]|Mutation=H': {'morph': 'Person=3|Number=Sing|Tense=Imperative[Mood?]|Mutation=H',
                                                                               'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Imperative[Mood?]|Mutation=Nasal': {'morph': 'Person=3|Number=Sing|Tense=Imperative[Mood?]|Mutation=Nasal',
                                                                                   'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Imperative[Mood?]|Mutation=Soft': {'morph': 'Person=3|Number=Sing|Tense=Imperative[Mood?]|Mutation=Soft',
                                                                                  'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Imp|Mutation=Aspirate': {'morph': 'Person=3|Number=Sing|Tense=Imp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Imp|Mutation=H': {'morph': 'Person=3|Number=Sing|Tense=Imp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Imp|Mutation=Nasal': {'morph': 'Person=3|Number=Sing|Tense=Imp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Imp|Mutation=Soft': {'morph': 'Person=3|Number=Sing|Tense=Imp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Past': {'morph': 'Person=3|Number=Sing|Tense=Past',
                                                       'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Past|Mutation=Aspirate': {'morph': 'Person=3|Number=Sing|Tense=Past|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Past|Mutation=H': {'morph': 'Person=3|Number=Sing|Tense=Past|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Past|Mutation=Nasal': {'morph': 'Person=3|Number=Sing|Tense=Past|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Past|Mutation=Soft': {'morph': 'Person=3|Number=Sing|Tense=Past|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Pqp': {'morph': 'Person=3|Number=Sing|Tense=Pqp',
                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Pqp|Mutation=Aspirate': {'morph': 'Person=3|Number=Sing|Tense=Pqp|Mutation=Aspirate',
                                                                        'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Pqp|Mutation=H': {'morph': 'Person=3|Number=Sing|Tense=Pqp|Mutation=H',
                                                                 'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Pqp|Mutation=Nasal': {'morph': 'Person=3|Number=Sing|Tense=Pqp|Mutation=Nasal',
                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Pqp|Mutation=Soft': {'morph': 'Person=3|Number=Sing|Tense=Pqp|Mutation=Soft',
                                                                    'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Pres': {'morph': 'Person=3|Number=Sing|Tense=Pres',
                                                       'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Pres|Mutation=Aspirate': {'morph': 'Person=3|Number=Sing|Tense=Pres|Mutation=Aspirate',
                                                                         'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Pres|Mutation=H': {'morph': 'Person=3|Number=Sing|Tense=Pres|Mutation=H',
                                                                  'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Pres|Mutation=Nasal': {'morph': 'Person=3|Number=Sing|Tense=Pres|Mutation=Nasal',
                                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=Pres|Mutation=Soft': {'morph': 'Person=3|Number=Sing|Tense=Pres|Mutation=Soft',
                                                                     'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=arall': {'morph': 'Person=3|Number=Sing|Tense=arall',
                                                        'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=arall|Mutation=Aspirate': {'morph': 'Person=3|Number=Sing|Tense=arall|Mutation=Aspirate',
                                                                          'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=arall|Mutation=H': {'morph': 'Person=3|Number=Sing|Tense=arall|Mutation=H',
                                                                   'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=arall|Mutation=Nasal': {'morph': 'Person=3|Number=Sing|Tense=arall|Mutation=Nasal',
                                                                       'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=arall|Mutation=Soft': {'morph': 'Person=3|Number=Sing|Tense=arall|Mutation=Soft',
                                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=bod_amherffaith': {'morph': 'Person=3|Number=Sing|Tense=bod_amherffaith',
                                                                  'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=bod_amherffaith|Mutation=Aspirate': {'morph': 'Person=3|Number=Sing|Tense=bod_amherffaith|Mutation=Aspirate',
                                                                                    'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=bod_amherffaith|Mutation=H': {'morph': 'Person=3|Number=Sing|Tense=bod_amherffaith|Mutation=H',
                                                                             'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=bod_amherffaith|Mutation=Nasal': {'morph': 'Person=3|Number=Sing|Tense=bod_amherffaith|Mutation=Nasal',
                                                                                 'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=bod_amherffaith|Mutation=Soft': {'morph': 'Person=3|Number=Sing|Tense=bod_amherffaith|Mutation=Soft',
                                                                                'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=bod_dyfodol': {'morph': 'Person=3|Number=Sing|Tense=bod_dyfodol',
                                                              'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=bod_dyfodol|Mutation=Aspirate': {'morph': 'Person=3|Number=Sing|Tense=bod_dyfodol|Mutation=Aspirate',
                                                                                'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=bod_dyfodol|Mutation=H': {'morph': 'Person=3|Number=Sing|Tense=bod_dyfodol|Mutation=H',
                                                                         'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=bod_dyfodol|Mutation=Nasal': {'morph': 'Person=3|Number=Sing|Tense=bod_dyfodol|Mutation=Nasal',
                                                                             'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=bod_dyfodol|Mutation=Soft': {'morph': 'Person=3|Number=Sing|Tense=bod_dyfodol|Mutation=Soft',
                                                                            'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=dibynnol_amherffaith': {'morph': 'Person=3|Number=Sing|Tense=dibynnol_amherffaith',
                                                                       'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Aspirate': {'morph': 'Person=3|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Aspirate',
                                                                                         'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=dibynnol_amherffaith|Mutation=H': {'morph': 'Person=3|Number=Sing|Tense=dibynnol_amherffaith|Mutation=H',
                                                                                  'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Nasal': {'morph': 'Person=3|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Nasal',
                                                                                      'pos': 'VERB'},
             'VBF__Person=3|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Soft': {'morph': 'Person=3|Number=Sing|Tense=dibynnol_amherffaith|Mutation=Soft',
                                                                                     'pos': 'VERB'},
             'VBF__Tense=Dibynnol': {'morph': 'Tense=Dibynnol', 'pos': 'VERB'},
             'VBF__Tense=Dibynnol|Mutation=Aspirate': {'morph': 'Tense=Dibynnol|Mutation=Aspirate',
                                                        'pos': 'VERB'},
             'VBF__Tense=Dibynnol|Mutation=H': {'morph': 'Tense=Dibynnol|Mutation=H',
                                                 'pos': 'VERB'},
             'VBF__Tense=Dibynnol|Mutation=Nasal': {'morph': 'Tense=Dibynnol|Mutation=Nasal',
                                                     'pos': 'VERB'},
             'VBF__Tense=Dibynnol|Mutation=Soft': {'morph': 'Tense=Dibynnol|Mutation=Soft',
                                                    'pos': 'VERB'},
             'VBF__Tense=Imp': {'morph': 'Tense=Imp', 'pos': 'VERB'},
             'VBF__Tense=Imperative[Mood?]': {'morph': 'Tense=Imperative[Mood?]',
                                               'pos': 'VERB'},
             'VBF__Tense=Imperative[Mood?]|Mutation=Aspirate': {'morph': 'Tense=Imperative[Mood?]|Mutation=Aspirate',
                                                                 'pos': 'VERB'},
             'VBF__Tense=Imperative[Mood?]|Mutation=H': {'morph': 'Tense=Imperative[Mood?]|Mutation=H',
                                                          'pos': 'VERB'},
             'VBF__Tense=Imperative[Mood?]|Mutation=Nasal': {'morph': 'Tense=Imperative[Mood?]|Mutation=Nasal',
                                                              'pos': 'VERB'},
             'VBF__Tense=Imperative[Mood?]|Mutation=Soft': {'morph': 'Tense=Imperative[Mood?]|Mutation=Soft',
                                                             'pos': 'VERB'},
             'VBF__Tense=Imp|Mutation=Aspirate': {'morph': 'Tense=Imp|Mutation=Aspirate',
                                                   'pos': 'VERB'},
             'VBF__Tense=Imp|Mutation=H': {'morph': 'Tense=Imp|Mutation=H', 'pos': 'VERB'},
             'VBF__Tense=Imp|Mutation=Nasal': {'morph': 'Tense=Imp|Mutation=Nasal',
                                                'pos': 'VERB'},
             'VBF__Tense=Imp|Mutation=Soft': {'morph': 'Tense=Imp|Mutation=Soft',
                                               'pos': 'VERB'},
             'VBF__Tense=Past': {'morph': 'Tense=Past', 'pos': 'VERB'},
             'VBF__Tense=Past|Mutation=Aspirate': {'morph': 'Tense=Past|Mutation=Aspirate',
                                                    'pos': 'VERB'},
             'VBF__Tense=Past|Mutation=H': {'morph': 'Tense=Past|Mutation=H',
                                             'pos': 'VERB'},
             'VBF__Tense=Past|Mutation=Nasal': {'morph': 'Tense=Past|Mutation=Nasal',
                                                 'pos': 'VERB'},
             'VBF__Tense=Past|Mutation=Soft': {'morph': 'Tense=Past|Mutation=Soft',
                                                'pos': 'VERB'},
             'VBF__Tense=Pqp': {'morph': 'Tense=Pqp', 'pos': 'VERB'},
             'VBF__Tense=Pqp|Mutation=Aspirate': {'morph': 'Tense=Pqp|Mutation=Aspirate',
                                                   'pos': 'VERB'},
             'VBF__Tense=Pqp|Mutation=H': {'morph': 'Tense=Pqp|Mutation=H', 'pos': 'VERB'},
             'VBF__Tense=Pqp|Mutation=Nasal': {'morph': 'Tense=Pqp|Mutation=Nasal',
                                                'pos': 'VERB'},
             'VBF__Tense=Pqp|Mutation=Soft': {'morph': 'Tense=Pqp|Mutation=Soft',
                                               'pos': 'VERB'},
             'VBF__Tense=Pres': {'morph': 'Tense=Pres', 'pos': 'VERB'},
             'VBF__Tense=Pres|Mutation=Aspirate': {'morph': 'Tense=Pres|Mutation=Aspirate',
                                                    'pos': 'VERB'},
             'VBF__Tense=Pres|Mutation=H': {'morph': 'Tense=Pres|Mutation=H',
                                             'pos': 'VERB'},
             'VBF__Tense=Pres|Mutation=Nasal': {'morph': 'Tense=Pres|Mutation=Nasal',
                                                 'pos': 'VERB'},
             'VBF__Tense=Pres|Mutation=Soft': {'morph': 'Tense=Pres|Mutation=Soft',
                                                'pos': 'VERB'},
             'VBF__Tense=arall': {'morph': 'Tense=arall', 'pos': 'VERB'},
             'VBF__Tense=arall|Mutation=Aspirate': {'morph': 'Tense=arall|Mutation=Aspirate',
                                                     'pos': 'VERB'},
             'VBF__Tense=arall|Mutation=H': {'morph': 'Tense=arall|Mutation=H',
                                              'pos': 'VERB'},
             'VBF__Tense=arall|Mutation=Nasal': {'morph': 'Tense=arall|Mutation=Nasal',
                                                  'pos': 'VERB'},
             'VBF__Tense=arall|Mutation=Soft': {'morph': 'Tense=arall|Mutation=Soft',
                                                 'pos': 'VERB'},
             'VBF__Tense=bod_amherffaith': {'morph': 'Tense=bod_amherffaith',
                                             'pos': 'VERB'},
             'VBF__Tense=bod_amherffaith|Mutation=Aspirate': {'morph': 'Tense=bod_amherffaith|Mutation=Aspirate',
                                                               'pos': 'VERB'},
             'VBF__Tense=bod_amherffaith|Mutation=H': {'morph': 'Tense=bod_amherffaith|Mutation=H',
                                                        'pos': 'VERB'},
             'VBF__Tense=bod_amherffaith|Mutation=Nasal': {'morph': 'Tense=bod_amherffaith|Mutation=Nasal',
                                                            'pos': 'VERB'},
             'VBF__Tense=bod_amherffaith|Mutation=Soft': {'morph': 'Tense=bod_amherffaith|Mutation=Soft',
                                                           'pos': 'VERB'},
             'VBF__Tense=bod_dyfodol': {'morph': 'Tense=bod_dyfodol', 'pos': 'VERB'},
             'VBF__Tense=bod_dyfodol|Mutation=Aspirate': {'morph': 'Tense=bod_dyfodol|Mutation=Aspirate',
                                                           'pos': 'VERB'},
             'VBF__Tense=bod_dyfodol|Mutation=H': {'morph': 'Tense=bod_dyfodol|Mutation=H',
                                                    'pos': 'VERB'},
             'VBF__Tense=bod_dyfodol|Mutation=Nasal': {'morph': 'Tense=bod_dyfodol|Mutation=Nasal',
                                                        'pos': 'VERB'},
             'VBF__Tense=bod_dyfodol|Mutation=Soft': {'morph': 'Tense=bod_dyfodol|Mutation=Soft',
                                                       'pos': 'VERB'},
             'VBF__Tense=dibynnol_amherffaith': {'morph': 'Tense=dibynnol_amherffaith',
                                                  'pos': 'VERB'},
             'VBF__Tense=dibynnol_amherffaith|Mutation=Aspirate': {'morph': 'Tense=dibynnol_amherffaith|Mutation=Aspirate',
                                                                    'pos': 'VERB'},
             'VBF__Tense=dibynnol_amherffaith|Mutation=H': {'morph': 'Tense=dibynnol_amherffaith|Mutation=H',
                                                             'pos': 'VERB'},
             'VBF__Tense=dibynnol_amherffaith|Mutation=Nasal': {'morph': 'Tense=dibynnol_amherffaith|Mutation=Nasal',
                                                                 'pos': 'VERB'},
             'VBF__Tense=dibynnol_amherffaith|Mutation=Soft': {'morph': 'Tense=dibynnol_amherffaith|Mutation=Soft',
                                                                'pos': 'VERB'},
             'VBF___': {'morph': '_', 'pos': 'VERB'},
             'VERBADJ___': {'morph': '_', 'pos': 'AUX'},
             'YNPRED__': {'morph': '_', 'pos': 'AUX'} # No idea about pos
             }
